apiVersion: v1
kind: Service
metadata:
  name: sdu-evac-backend
  labels:
    app: sdu-evac-backend
spec:
  selector:
    app: sdu-evac-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer