apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sdu-evac-backend
  name: sdu-evac-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdu-evac-backend
  template:
    metadata:
      labels:
        app: sdu-evac-backend
    spec:
      containers:
        - name: sdu-evac-backend
          image: gcr.io/emapp-366911/backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGO_DB_CONNECTION_STRING
              value: mongodb+srv://mani320:l2ZyYYmOaS96J6Hm@cluster0.tqvcz7j.mongodb.net/test
            - name: MONGO_DB_NAME
              value: Cluster0
            - name: REDIS_URI
              value: rediss://default:AVNS_EgU9d0IcwBhOBbOQIQ2@redis-1e31c318-mnhnielsen-8447.aivencloud.com:12577
