apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sdu-evac-frontend
  name: sdu-evac-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdu-evac-frontend
  template:
    metadata:
      labels:
        app: sdu-evac-frontend
    spec:
      containers:
        - name: sdu-evac-frontend
          image: gcr.io/emapp-366911/frontend:latest
          ports:
            - containerPort: 80
